version: '2'

services:

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - flask

    flask:
        build: .
        ports:
            - "8000:8000"
        volumes:
          - .:/code

        entrypoint: uwsgi --ini /code/etc/api.ini
        depends_on:
            - mongo

    mongo:
        image: mongo:3.4.0
        volumes:
            - ./db:/data/db
        ports:
            - "27017:27017"
